### ISSUE TITLE
Can you explain how to deploy this project

### ISSUE THREAD

**Issue by K2086117L** [anubhavjana/DAGit#1]

**Comment by anubhavjana** [comment]
Sure, Thanks for connecting.
This is the old repo for DAGit.
Requesting you to raise the issue on https://github.com/anubhavjana/DAGit-Serverless-Applications-as-a-Service.
For more information about the platform, please refer to the paper "DAGit: A Platform For Enabling Serverless Applications" on the same repo link. 
Will be updating the repo soon.
Thanks
Anubhav
